version: "3.9"
services:
  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18028:8028"
    networks:
      - myapp-net
    environment:
      - host-code=database
      - service-port=3306
      - db-name=finaldb
      - db-user=root
      - db-password=big185678
      - server-port=8028
    volumes:
      - /shared/news:/usr/news
    depends_on:
      - AI_api

  AI_api:
    image: hena07/model_api
    ports:
      - "8000:8000"
    networks:
      - myapp-net
    volumes:
      - ./run_api.sh:/usr/local/bin/run_api.sh
    command: >
      sh -c "ls -l /usr/local/bin/run_api.sh && chmod +x /usr/local/bin/run_api.sh && /usr/local/bin/run_api.sh"
    privileged: true

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
      - springboot
    networks:
      - myapp-net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  database:
    image: hena07/centos_hn_v3
    ports:
      - "3306:3306"
    networks:
      - myapp-net
    privileged: true

  airflow_kafka:
    image: hena07/dataprocess:0
    ports:
      - "18080:8080"
      - "18081:8081"
    volumes:
      - ./run_conda.sh:/usr/local/bin/run_conda.sh
      - /shared/news:/usr/local/news
    networks:
      - myapp-net
    privileged: true

  redis:
    image: hena07/redis_rocky:2
    ports:
      - "6379:6379"
    networks:
      - myapp-net

networks:
  myapp-net:
    driver: bridge
