version : '3.8'
services:
  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '18082:8082'
    depends_on:
      - database
      - redis
    networks:
      - myapp-net
    env_file:
      - envfile.env

  nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80'
    depends_on:
      - springboot
    networks:
      - myapp-net

  database:
    image: hena07/centos_hn_v3:live
    ports:
      - '3306:3306'
    networks:
      - myapp-net

  airflow_kafka:
    image: hena07/dataprocess:0
    ports:
      - '18080:8080'
      - '18081:8081'
    depends_on:
      - database
    volumes:
      - /usr/local/news:/shared/news
    networks:
      - myapp-net

  redis:
    image: hena07/redis_rocky
    ports:
      - '6379:6379'
    networks:
      - myapp-net

  AIapi:
    image: hena07/model_api:2
    ports:
      - '8000:8000'
    networks:
      - myapp-net
    depends_on:
      - springboot
    command: >
      /bin/bash -c "cd /usr/local/etc/ModelAPI &&
      conda activate tensorflow_cuda &&
      uvicorn main:app --host=0.0.0.0
    

networks:
  myapp-net:
    driver: bridge



