name: continuous_deployment_test
on:
  push:
    branches:
      - naverlogin
    paths-ignore:
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          tags: hena07/myspringprojects:latest
          push: true

  deploy:
    runs-on: ubuntu-20.04
    needs: build

    steps:
      - name: Deploy to GCP VM
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/salva/jeronimo # 레포지토리가 클론된 경로
            docker-compose down springboot    # 기존 컨테이너를 내림
            docker-compose pull springboot     # 최신 이미지 가져오기
            docker-compose up springboot  -d    # 서비스 실행